"""add_timezone_support_to_agents_table

Revision ID: 03e9467c1c5a
Revises: deddb1747453
Create Date: 2025-11-24 14:07:47.657402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e9467c1c5a'
down_revision: Union[str, Sequence[str], None] = 'deddb1747453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
