"""add_security_platform_tables

Revision ID: c199e43193b6
Revises: 9e995409f50e
Create Date: 2025-11-29 23:43:51.922614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199e43193b6'
down_revision: Union[str, Sequence[str], None] = '9e995409f50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_scopes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('ip_ranges', sa.JSON(), nullable=True),
    sa.Column('excluded_ips', sa.JSON(), nullable=True),
    sa.Column('allowed_ports', sa.JSON(), nullable=True),
    sa.Column('testing_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('testing_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_concurrent_scans', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=True),
    sa.Column('authorized_by', sa.String(length=255), nullable=True),
    sa.Column('authorization_document', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(length=100), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevelenum'), nullable=False),
    sa.Column('approver_name', sa.String(length=255), nullable=False),
    sa.Column('approver_email', sa.String(length=255), nullable=True),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approval_comments', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pentesting_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('current_phase', sa.Enum('RECONNAISSANCE', 'SCANNING', 'ENUMERATION', 'VULNERABILITY_ASSESSMENT', 'EXPLOITATION', 'POST_EXPLOITATION', 'REPORTING', name='pentestphaseenum'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tree_id', sa.String(length=100), nullable=True),
    sa.Column('primary_target', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('critical_findings_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['engagement_scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pentesting_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Enum('RECONNAISSANCE', 'SCANNING', 'ENUMERATION', 'VULNERABILITY_ASSESSMENT', 'EXPLOITATION', 'POST_EXPLOITATION', 'REPORTING', name='pentestphaseenum'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tool_required', sa.String(length=100), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevelenum'), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['pentesting_tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pentesting_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('action_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('hash_chain', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pentesting_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevelenum'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('affected_component', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('exploit_available', sa.Boolean(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pentesting_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['pentesting_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_findings')
    op.drop_table('security_audit_logs')
    op.drop_table('pentesting_tasks')
    op.drop_table('pentesting_sessions')
    op.drop_table('human_approvals')
    op.drop_table('engagement_scopes')
    # ### end Alembic commands ###
