"""remove_legacy_user_columns_and_fix_schema

Revision ID: c5ae20a2a317
Revises: 8809d62b9ac2
Create Date: 2025-12-04 01:19:49.994210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ae20a2a317'
down_revision: Union[str, Sequence[str], None] = '8809d62b9ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'created_by')
    op.drop_index(op.f('ix_artifacts_user_id'), table_name='artifacts')
    op.drop_column('artifacts', 'user_id')
    op.drop_column('engagement_scopes', 'created_by')
    op.alter_column('human_approvals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('human_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('human_approvals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_human_approvals_status'), table_name='human_approvals')
    op.drop_column('knowledge_entries', 'created_by')
    op.drop_column('pentesting_sessions', 'authorized_users')
    op.drop_column('pentesting_tasks', 'assigned_to')
    op.drop_column('security_audit_logs', 'user_id')
    op.drop_column('security_findings', 'discovered_by')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_column('sessions', 'user_id')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.add_column('security_findings', sa.Column('discovered_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('security_audit_logs', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pentesting_tasks', sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pentesting_sessions', sa.Column('authorized_users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_entries', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_human_approvals_status'), 'human_approvals', ['status'], unique=False)
    op.alter_column('human_approvals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('human_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('human_approvals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('engagement_scopes', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_artifacts_user_id'), 'artifacts', ['user_id'], unique=False)
    op.add_column('agents', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
